app1/urls.py
from django.urls import path
from app1.views import *
app_name='raj'
urlpatterns = [
    path('cond/',cond,name='cond'),
    
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='prasad'
urlpatterns = [
    path('loop/',loop,name='loop'),
    
]

specific_urlnavigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    
    
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def cond(request):
    d={'a':5,'b':7}
    return render(request,'cond.html',d)

app2/views.py
from django.shortcuts import render

# Create your views here.
def loop(request):
    d={'name':'Rajendra'}
    return render(request,'loop.html',d)

templates/cond.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Perfoming conditional Statment Representation</h1>
        {% if a > b %}
        <h1>{{a}} is maximum {{b}}</h1>
        {% else %}
        <h1>{{b}} is maximum than {{a}}</h1>
        {% endif %}
        <a href="{% url 'prasad:loop' %}">Navigate from cond to loop</a>
        
    </center>
</body>
</html>

templates/loop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Looping Representation </h1>
        {% for i in name  %}
        <h1>{{i}}</h1>
        {% endfor %}
        <a href="{% url 'raj:cond' %}">Navigate from loop to cond</a>

    </center>
</body>
</html>